sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"
  - "$HOME/.stack"
  - "$TRAVIS_BUILD_DIR/.stack-work"

matrix:
  include:
  - ghc: 8.6.5
  - ghc: 8.8.2
  
  - ghc: 8.6.5
    env: STACK_YAML="$TRAVIS_BUILD_DIR/stack.yaml"

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint . -XTypeApplications

  - |
    if [ -z "$STACK_YAML" ]; then
      cabal update
      travis_wait 30 cabal build --enable-tests --enable-benchmarks --write-ghc-environment-files=always
    else
      curl -sSL https://get.haskellstack.org/ | sh
      stack --version
      travis_wait 30 stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --ghc-options=-Werror
    fi

script:
  - |
    if [ -z "$STACK_YAML" ]; then
      travis_wait 120 cabal test --enable-tests
    else
      travis_wait 120 stack test --system-ghc
    fi

notifications:
  email: false
